version: "2"
services:
  proxy:
    build: ./
    networks:
      - env_api
      - frontend
    ports:
      - "80:80"

networks:
  env_api:
    external:
      name: api-env_default
  frontend:
    external:
      name: site-prefeitura_default